default:
    name: fire

#intern genutzer Name des skins
fire:
    #Anzeigename des Skins
    name: fire
    #config_file wird auch als id in der Datenbank verwendet um den Skin zu identifizieren.
    config_file: fire

doom:
    #Anzeigename des Skins
    name: doom
    #config_file wird auch als id in der Datenbank verwendet um den Skin zu identifizieren.
    config_file: doom
